fileshare/config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items, only: [:index, :new, :create, :destroy]
   root "items#index"
end
#get 'item/index'
 # get 'item/new'
  #get 'item/create'
  #get 'item/destroy'

fileshare/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fileshare/app/models/item.rb
class Item < ActiveRecord::Base
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
    validates :name, presence: true # Make sure the owner's name is present.
 end

fileshare/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

fileshare/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
      
      if @item.save
         redirect_to items_path, notice: "The item #{@item.name} has been uploaded."
      else
         render "new"
      end
  end

  def destroy
    @item = Item.find(params[:id])
      @item.destroy
      redirect_to items_path, notice:  "The item #{@item.name} has been deleted."
   end
   
   private
      def item_params
      params.require(:item).permit(:name, :attachment)
   end
end

fileshare/app/helpers/application_helper.rb
module ApplicationHelper
end

fileshare/app/helpers/item_helper.rb
module ItemHelper
end

fileshare/app/views/items/create.html.erb
<h1>Item#create</h1>
<p>Find me in app/views/item/create.html.erb</p>

fileshare/app/views/items/destroy.html.erb
<h1>Item#destroy</h1>
<p>Find me in app/views/item/destroy.html.erb</p>

fileshare/app/views/items/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "New File", new_item_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @items.each do |item| %>
         
         <tr>
            <td><%= item.name %></td>
            <td><%= link_to "Download File", item.attachment_url %></td>
            <td><%= button_to "Delete",  item, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{item.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>

fileshare/app/views/items/new.html.erb
<% if !@item.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @item, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>

fileshare/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   
   <head>
      <title>Fileshare</title>
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
   </head>
   
   <body>
      <div class = "container" style = "padding-top:20px;">
         <%= yield %>
      </div>
   </body>

</html>